### ISSUE TITLE
Readme.md updates

### ISSUE THREAD

**Issue by ColinSullivan1** [Logimethods/nats-connector-spark#1]
Thanks for the NATS contribution, The code and tests looks great!

A few requests for readme.md:
- Could you link back to nats.io?  For example: This is an Apache Spark integration with [NATS](http://www.nats.io), a highly performant cloud native messaging system.
- Could you provide a high level overview and some instructions for use, and perhaps mention that [gnatsd](http://nats.io/download/nats-io/gnatsd/) is required for the unit tests?
- Also provide some info about configuration - e..g how/where to configure this for NATS and Apache spark?

MIT license is great.

Again, thanks!

**Comment by laugimethods** [comment]
Please have a look at the new README file (work still in progress).
Don't hesitate to make any further comments (including about the English language).

**Comment by ColinSullivan1** [comment]
LGTM!
